### ISSUE TITLE
Handle error of pre-quota balances that dip below zero

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile#296]
Accounts that preexisted quotas were marked with consuming 0 resources at the start of quotas.

This introduced a bug where if they remove any storage they will hit an error for going below a 0 size.

Contributions to the solution:

- [ ] Include a bucket version when created. This is a long-term strategy that will help in the future detect any introduced differences, handle migrations, etc. https://github.com/textileio/textile/issues/293
- [ ] Track bucket size in the bucket schema. These sizes are generally useful, since as an end user I want to know what amount is taken by any bucket at any time. https://github.com/textileio/textile/issues/294
- [ ] Recalc bucket size if it ever hits zero, to ensure any accounting errors are audited before throwing an error. https://github.com/textileio/textile/issues/295
